name: base
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - pandas
  - matplotlib
  - shapely
  - requests
  - configobj
  - netcdf4
  - xarray
  - pytables
  - pytest
  - seaborn
  - pip
  - geopandas
  - pip:
      - oggm
      - SALib
      - git+https://github.com/OGGM/oggm-edu
      - cartopy
      - salem
      - rasterio
      - scikit-image
